#!/bin/sh

# Source system xinitrc scripts (keyboard, dbus, etc.)
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Start D-Bus session if not already running
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

# Export for child processes
export DBUS_SESSION_BUS_ADDRESS
export DBUS_SESSION_BUS_PID

# XDG dirs
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/tmp/xdg-runtime-$(id -u)}"
mkdir -p "$XDG_RUNTIME_DIR"
chmod 0700 "$XDG_RUNTIME_DIR"

# gvfs virtual filesystem daemon
/usr/lib/gvfsd &
/usr/lib/gvfsd-fuse "$XDG_RUNTIME_DIR/gvfs" -f &

# Polkit authentication agent (needed for mounting, admin actions)
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &


export EDITOR="vim"
export TERMINAL="st"
export BROWSER="firefox"

export VDPAU_DRIVER=va_gl
export LIBVA_DRIVER_NAME=iHD
#export MOZ_DISABLE_RDD_SANDBOX=1
#export MOZ_X11_EGL=1
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_X11_NO_MITSHM=1

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export _JAVA_AWT_WM_NONREPARENTING=1
export GTK_THEME=Dracula-slim
export GTK_ICON_THEME=dracula-icons

sudo virsh net-start default &
xset r rate 300 50 &
dwm_bar &
dunst &
#unclutter &
sxhkd &
#xwallpaper --zoom ~/pix/wall/arch.png
xwallpaper --zoom pix/ss/1763622050.jpg
xcompmgr &

# Start dwm (with dbus-launch wrapping the session)
exec dbus-launch --exit-with-session dwm

#exec dwm
#exec dwm_systray
#xrandr --output HDMI1 --mode 640x480 --output eDP-1 --mode 1920x1080 --left-of HDMI1 &
#xwallpaper --zoom ~/pix/wall/arch.png
#exec startxfce4

